{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[{"sourceId":10496674,"sourceType":"datasetVersion","datasetId":6499058}],"dockerImageVersionId":30839,"isInternetEnabled":false,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# This Python 3 environment comes with many helpful analytics libraries installed\n# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n# For example, here's several helpful packages to load\n\nimport numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\n# Input data files are available in the read-only \"../input/\" directory\n# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n\nimport os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        # print(os.path.join(dirname, filename))\n        pass\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","trusted":true,"execution":{"iopub.status.busy":"2025-01-18T11:15:45.606984Z","iopub.execute_input":"2025-01-18T11:15:45.60743Z","iopub.status.idle":"2025-01-18T11:15:49.8315Z","shell.execute_reply.started":"2025-01-18T11:15:45.607392Z","shell.execute_reply":"2025-01-18T11:15:49.830202Z"}},"outputs":[],"execution_count":1},{"cell_type":"code","source":"pip install absl-py==1.1.0 aiohttp==3.8.1 aiosignal==1.2.0 async-timeout==4.0.2 attrs==21.4.0 cachetools==5.2.0 certifi==2022.6.15 charset-normalizer==2.1.0 cycler==0.11.0 filelock==3.7.1 fonttools==4.34.4 frozenlist==1.3.0 fsspec==2022.5.0 google-auth==2.9.0 google-auth-oauthlib==0.4.6 grpcio==1.47.0 huggingface-hub==0.8.1 HyperPyYAML==1.0.1 idna==3.3 importlib-metadata==4.12.0 joblib==1.2.0 kiwisolver==1.4.3 llvmlite==0.38.1 Markdown==3.3.7 matplotlib==3.5.2 multidict==6.0.2 numba==0.55.2 numpy==1.22.4 oauthlib==3.2.1 packaging==21.3 pandas==1.4.3 Pillow==9.2.0 protobuf==3.19.5 pyasn1==0.4.8 pyasn1-modules==0.2.8 pyDeprecate==0.3.2 pyparsing==3.0.9  python-speech-features==0.6 pytorch-lightning==1.6.4 pytz==2022.1 ","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-01-18T11:15:49.833024Z","iopub.execute_input":"2025-01-18T11:15:49.83356Z","iopub.status.idle":"2025-01-18T11:19:10.987762Z","shell.execute_reply.started":"2025-01-18T11:15:49.833518Z","shell.execute_reply":"2025-01-18T11:19:10.986455Z"}},"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7be62dd24370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/absl-py/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7be62dd246a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/absl-py/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7be62dd24940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/absl-py/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7be62dd24af0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/absl-py/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7be62dd24ca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/absl-py/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement absl-py==1.1.0 (from versions: none)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for absl-py==1.1.0\u001b[0m\u001b[31m\n\u001b[0mNote: you may need to restart the kernel to use updated packages.\n","output_type":"stream"}],"execution_count":2},{"cell_type":"code","source":"%pip install PyYAML==6.0 requests==2.28.1 requests-oauthlib==1.3.1 resampy==0.3.0 rsa==4.8 ruamel.yaml==0.17.21 ruamel.yaml.clib==0.2.6 scikit-learn==1.1.1 scipy==1.8.1 seaborn==0.12.0 sentencepiece==0.1.96 six==1.16.0 sklearn==0.0 speechbrain==0.5.12 tensorboard==2.9.1 tensorboard-data-server==0.6.1 tensorboard-plugin-wit==1.8.1 threadpoolctl==3.1.0 torch==1.11.0 torch-tb-profiler==0.4.0 torchaudio==0.11.0 torchmetrics==0.9.1 torchvision==0.12.0 tqdm==4.64.0 typing-extensions==4.2.0 urllib3==1.26.9 Werkzeug==2.1.2 yarl==1.7.2 zipp==3.8.0","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-01-18T11:19:10.989954Z","iopub.execute_input":"2025-01-18T11:19:10.990322Z","iopub.status.idle":"2025-01-18T11:22:31.701739Z","shell.execute_reply.started":"2025-01-18T11:19:10.990281Z","shell.execute_reply":"2025-01-18T11:22:31.700288Z"}},"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7910c0d6ee00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7910c0d6f130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7910c0d6f3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7910c0d6f580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7910c0d6f730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement PyYAML==6.0 (from versions: none)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for PyYAML==6.0\u001b[0m\u001b[31m\n\u001b[0mNote: you may need to restart the kernel to use updated packages.\n","output_type":"stream"}],"execution_count":3},{"cell_type":"code","source":"%pip install speechbrain","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-01-18T11:32:33.69882Z","iopub.execute_input":"2025-01-18T11:32:33.699179Z","iopub.status.idle":"2025-01-18T11:35:54.388709Z","shell.execute_reply.started":"2025-01-18T11:32:33.699142Z","shell.execute_reply":"2025-01-18T11:35:54.387117Z"}},"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7cda9584f970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/speechbrain/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7cda9584fca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/speechbrain/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7cda9584ff40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/speechbrain/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7cda9587c040>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/speechbrain/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7cda9587c2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/speechbrain/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement speechbrain (from versions: none)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for speechbrain\u001b[0m\u001b[31m\n\u001b[0mNote: you may need to restart the kernel to use updated packages.\n","output_type":"stream"}],"execution_count":7}]}